server:
  port: 8092
spring:
  profiles:
    active: ${APP_ACTIVE_PROFILE}
  application:
    name: blogs
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      #      max-file-size: 128KB
      #      max-request-size: 128KB
      enabled: true

app:
  jwt:
    secret-key: ${APP_JWT_SECRET_KEY}
    token-validity: ${APP_JWT_TOKEN_VALIDITY}
  upload:
    base-folder: public
    thumbnail-location: uploads/thumbnails

