spring:
  application:
    name: blogs
  datasource:
    url: jdbc:mysql://localhost:3306/spring_blogs?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      #      max-file-size: 128KB
      #      max-request-size: 128KB
      location: static/media/blog_attachment
      enabled: true
